# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00d1aa2972bc3faedcb66364d58dd2b20400cdaff6e93c11ab16a9a9689f974d27f0b03489fee2c4a157efa7116d56c1e3796678e43c25bfea583938abdd5215

test:
  secret_key_base: 3d79075f397b7fa60969ae86a6bb0e19cb79ba77d742a26269386e0075e12452094e7ead0a9e1d558808786d0f9df99746b988bbc2e1193ce88af62a556ac093

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
